Game.create!([
  {title: "Tom Clancy's The Division - Xbox One", description: "Seamless Multiplayer: The Dark Zone - Collaborate with other players, or attack and steal their loot.\r\nA Living, Breathing World - Use the environment for strategic advantages to dominate fights and ambush your enemies.\r\nUrban Jungle - Fight the Cleaners who wield flamethrowers, take on thugs who roam the city, and encounter enemy factions.\r\nGear Up and Customize Your Agent - Customize your agent and your backpack. Level up your weapons, gear, and skills.\r\nCutting-Edge Tech - Choose and upgrade your skills, and synergize with teammates to increase your chances of winning in combat.", developer: "Red Storm Entertainment", publisher: "Ubisoft", rating: "MA15+", user_id: 1, genre_id: 4, game_img_file_name: "the_division.jpg", game_img_content_type: "image/jpeg", game_img_file_size: 422579, game_img_updated_at: "2016-03-29 10:24:43"},
  {title: "Metal Gear Solid V: The Phantom Pain - PlayStation 4", description: "Open-World game design allowing players ultimate freedom on how to approach missions and overall game progression\r\nFox Engine delivers photorealistic graphics, thoughtful game design and true new-generation game production quality\r\nOnline connectivity that carries the experience beyond the consoles to other devices to augment the overall functionality and access to the game", developer: "Kojima Productions", publisher: "Konami", rating: "R18+", user_id: 2, genre_id: 2, game_img_file_name: "mgsv.jpg", game_img_content_type: "image/jpeg", game_img_file_size: 323495, game_img_updated_at: "2016-03-29 10:22:52"},
  {title: "Halo 5: Guardians", description: "Xbox Live subscription required for online play.\r\nIntense story on a galactic scale: Play as the Master Chief and Spartan Locke across three new worlds.\r\nYour team is your weapon: Play solo or with friends in a 4-player co-op experience.\r\nWarzone: New, 24-player massive-scale multiplayer mode.\r\nArena: Pure, skill-based 4-vs-4 competitive combat.\r\nNew rewards system: Earn Requisition Points to redeem for new gear.\r\nExtensive multiplayer content: Receive more than 15 new free maps and earn fresh, new content like weapons and gear, each month after launch.", developer: "343 Industries", publisher: "Microsoft Studios", rating: "MA15", user_id: 2, genre_id: 1, game_img_file_name: "halo-5.jpg", game_img_content_type: "image/jpeg", game_img_file_size: 208397, game_img_updated_at: "2016-03-29 10:23:21"},
  {title: "The Last of Us Remastered - PlayStation 4", description: "Winner of over 200 Game of the Year awards\r\nExplore a brutal post-pandemic world, fully realized with the power of PlayStation 4 system\r\nIncludes all DLC packs: over $30 in value\r\nIn-game cinematic commentary from the cast and creative director", developer: "Naughty Dog", publisher: "Sony Computer Entertainment", rating: "R18+", user_id: 1, genre_id: 2, game_img_file_name: "thelastofus.jpg", game_img_content_type: "image/jpeg", game_img_file_size: 216063, game_img_updated_at: "2016-03-29 10:24:16"},
  {title: "Star Wars: Battlefront - Xbox One", description: "Visit classic planets from the original Star Wars trilogy, detailed with an unprecedented amount of realism and sense of authenticity that will transport you to a galaxy far, far away\r\nPilot a diverse set of ground-based vehicles including nimble speeder bikes, massive AT-ATs, and more\r\nEncounter a variety of beloved characters from the original trilogy such as C-3PO and R2-D2\r\nPilot the Millennium Falcon, X-wings, TIE fighters, and more of your favorite vehicles in exhilarating aerial combat\r\nBattle alongside your friends online or in offline split-screen Co-op mode", developer: "DICE", publisher: "EA Games", rating: "M15", user_id: 1, genre_id: 1, game_img_file_name: "battlefront.jpg", game_img_content_type: "image/jpeg", game_img_file_size: 180685, game_img_updated_at: "2016-03-29 10:24:29"},
  {title: "The Witcher 3: Wild Hunt - PlayStation 4", description: "In the past he has raised and overthrown monarchs, battled legendary monsters and saved the lives of many. Now Geralt embarks on his most personal quest to save his loved ones and protect the world from an ancient threat.\r\nThe story is drawn based on player decisions. Each action will have consequences which change the story and the game world. NPCs, communities, monsters and locations all change, based on player choice.\r\nThe Witcher 3 is standalone adventure, easily entered into by new players. Witcher fans will find subtle references to their adventures, but these elements are not necessary to enjoy the game fully.\r\nA breathtaking cinematic introduction demonstrating the game background - this puts players immediately in the know about the situation in the war-ravaged Northern Kingdoms and the background story of the main character.\r\nUnique atmosphere, memorable characters and gritty dialog - the game world has its own unique feel. It is a classic dark fantasy tale that will appeal to fans of all kinds of fantasy stories.", developer: "CD Projekt Red", publisher: "WB Games", rating: "R18+", user_id: 2, genre_id: 4, game_img_file_name: "the_witcher.jpg", game_img_content_type: "image/jpeg", game_img_file_size: 382866, game_img_updated_at: "2016-03-29 10:20:26"},
  {title: "Monster Hunter 4 Ultimate Standard Edition - Nintendo 3DS", description: "Online Play - Connect with up to three other hunters online over the Nintendo Network for the first time ever, or local wireless, to join up and take down larger than life beasts.\r\nTwo new weapon classes - The Insect Glaive is a long staff type weapon accompanied by a powerful flying insect which can be customized with various attributes; the Charge Blade is a hybrid that switches between a sword and shield or axe mode.\r\nMore vertical environments - The action expands with more fluid climbing motions and the addition of jump attacks from walls or ledges.\r\nNew gameplay mechanic - For the first time ever, hop on to monsters and hold on to deliver a burst of attacks\r\nReturning favorites and fresh challenges - Brand new monsters such as the dark and menacing Gore Magala as well as hordes of returning favorites including the primal Tigrex, players have access to the largest roster of ferocious enemies than ever before.", developer: "Capcom", publisher: "Capcom", rating: "M15", user_id: 1, genre_id: 3, game_img_file_name: "mh4u.jpg", game_img_content_type: "image/jpeg", game_img_file_size: 419429, game_img_updated_at: "2016-03-29 10:23:58"}
])
Genre.create!([
  {name: "Action"},
  {name: "Action-Adventure"},
  {name: "Adventure"},
  {name: "Role-Playing"},
  {name: "Simulation"},
  {name: "Strategy"},
  {name: "Sports"}
])
Review.create!([
  {rating: 5, comment: "Amazing Game! Hours of Enjoyment!", user_id: 1, game_id: 9},
  {rating: 4, comment: "Game was good. Gave me hours of enjoyment!", user_id: 1, game_id: 9},
  {rating: 5, comment: "CD Projekt Red have done an amazing job with this game! ", user_id: 1, game_id: 9},
  {rating: 2, comment: "Game was poorly optimised for consoles.", user_id: 1, game_id: 9},
  {rating: 3, comment: "Game was ok. There was too much content and I felt overwhelmed at times playing it.", user_id: 1, game_id: 9},
  {rating: nil, comment: nil, user_id: nil, game_id: nil}
])
